### ISSUE TITLE
publishing to pypi seems broken

### ISSUE THREAD

**Issue by olivierdalang** [opengisch/pirogue#12]
Strangely,  1.3.0 is listed on pypi, but not found with pip install

Upon inspection, it seems 1.3.0 misses the .tar.gz : https://pypi.org/simple/pirogue/

The workflow outputs `It looks like there are no Python distribution packages to publish in the directory 'dist/'. Please verify that they are in place should you face this problem.`

Probably something went wrong when updating the workflows

**Comment by 3nids** [comment]
not sure exactly what happened, but this should be fixed now.
1.3.3 has been released.

**Comment by olivierdalang** [comment]
Hmm it looks like it's still the same...

`pip install pirogue==1.3.3` fails too. If you look at https://pypi.org/simple/pirogue/ you'll see there's no `pirogue-1.3.3.tar.gz`.

I think the PR would work.
